# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fea8388680edd29adafb3c69205cf2a6acf627f6863b89e1320b8672add846f1eab8a7531fd8ba7878f97dd5c20fcc99d68f66e0ba1fb38e5c172a3d5f31957

test:
  secret_key_base: 066ca67d22cc5b5ce53a05d98b249a5fd11780d9cc77100c8779b86e537b3f92fbfeb9c16e9ddd1d518c87a062abb87253f0b508f4b6a3ad68813d07529c740e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
